### Агрегирование продаж и возвратов

##### Дан датафрейм

In [1]:
import pandas as pd

In [2]:
t = [
    {'Shop': "Yakimanka", 'Employee': "Anna", 'Type': 1, 'Sum': 528},
    {'Shop': "Yakimanka", 'Employee': "Fedor", 'Type': 2, 'Sum': 632},
    {'Shop': "Butovo", 'Employee': "Peter", 'Type': 1, 'Sum': 115},
    {'Shop': "Yakimanka", 'Employee': "Anna", 'Type': 1, 'Sum': 1024},
    {'Shop': "Butovo", 'Employee': "Peter", 'Type': 1, 'Sum': 1754},
    {'Shop': "Butovo", 'Employee': "Peter", 'Type': 1, 'Sum': 111},
    {'Shop': "Kamenka", 'Employee': "Max", 'Type': 1, 'Sum': 499},
    {'Shop': "Kamenka", 'Employee': "Max", 'Type': 2, 'Sum': 23},
    {'Shop': "Butovo", 'Employee': "Jugen", 'Type': 1, 'Sum': 214},
    {'Shop': "Kamenka", 'Employee': "Max", 'Type': 1, 'Sum': 964},
    {'Shop': "Yakimanka", 'Employee': "Fedor", 'Type': 2, 'Sum': 100},
    {'Shop': "Butovo", 'Employee': "Jugen", 'Type': 1, 'Sum': 10000}
]

df = pd.DataFrame(t)

In [3]:
df

         Shop Employee  Type    Sum
0   Yakimanka     Anna     1    528
1   Yakimanka    Fedor     2    632
2      Butovo    Peter     1    115
3   Yakimanka     Anna     1   1024
4      Butovo    Peter     1   1754
5      Butovo    Peter     1    111
6     Kamenka      Max     1    499
7     Kamenka      Max     2     23
8      Butovo    Jugen     1    214
9     Kamenka      Max     1    964
10  Yakimanka    Fedor     2    100
11     Butovo    Jugen     1  10000

##### Задание:
Сделать сводную таблицу и расчитать:
  - Количество операций
  - Сумму
  - Среднее

In [4]:
( df.groupby(['Shop', 'Employee', 'Type'])['Sum']
    .agg( Amount=('count'), Sum=('sum'), Avg=('mean') )
        .sort_values(['Sum'], ascending=False).reset_index() )

        Shop Employee  Type  Amount    Sum     Avg
0     Butovo    Jugen     1       2  10214  5107.0
1     Butovo    Peter     1       3   1980   660.0
2  Yakimanka     Anna     1       2   1552   776.0
3    Kamenka      Max     1       2   1463   731.5
4  Yakimanka    Fedor     2       2    732   366.0
5    Kamenka      Max     2       1     23    23.0